mastodon:
  access_token: ${MASTODON_ACCESS_TOKEN}
  mastodon_instance: https://swiss.social
  mastodon_username: ping13
  feed_item_limit: 5
  types:
    - favourites
#    - bookmarks
rss:
  urls:
    - url: https://bookmarks.ping13.net/feeds/${LINKDING_ID}/all
      tag: linkding
    # - url: https://feedbin.com/starred/${FEEDBIN_ID}.xml
    #   tag: feedbin
 #github:
#  starfeed: https://api.github.com/users/ping13/starred

